So I don't really now how to do this shit because I am horrable at socializing, and have been an open-source dev all my live.
I do it for my passion, and curiousity NOT to be paid, that's why I am broke all the time.
But if anyone would like to colarbaotte free or paid I would be very willing and apprecaite it! :D
